#!/usr/bin/env bash
#
# Copyright (c) 2019 Florian Xaver
#
# MIT License: see File LICENSE
#
 mpstat -P ALL -o JSON 1 1 | jq -r '[.sysstat.hosts[0].statistics[]."cpu-load"[]] | sort_by(.usr)[-8:-1][] | "cpu" + .cpu + " " + (.usr | tostring) + "%"' | tr '\n' ' '

